version: "3"
services:
  go:
    image: golang:1.9.2-alpine
    container_name: go-pratice_go
    volumes:
      - ./go:/go
    links:
      - postgres:postgres
    ports:
      - "8080:8080"
    # command: go run /go/src/fasthttp.go -addr :8080 -compress true
    # command: go run /go/src/fasthttprouter.go
    # command: go run /go/src/web.go
    # command: go run /go/src/websocket.go
    tty: true
  postgres:
    image: postgres:9.6.5-alpine
    container_name: go-pratice_postgres
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test
